import { Mermaid } from "@/components/mermaid";
import { buildInfo } from "@/lib/build";

export const KEY_FILES = [
  { path: "src/lib/seal.ts", why: "The only code that locks and unlocks your key." },
  {
    path: "src/lib/oauth/authorize.ts",
    why: "Takes your key from the connect page, checks it with EdgeOS, seals it.",
  },
  {
    path: "src/lib/edgeos/client.ts",
    why: "The only place your key is sent anywhere: to EdgeOS, as you.",
  },
  {
    path: "src/lib/scrub.ts",
    why: "Removes any key from error messages before a model sees them.",
  },
  {
    path: "src/mcp/lib/tool-wrapper.ts",
    why: "Logs each call without arguments, bodies or keys.",
  },
];

export function Plain() {
  return (
    <div className="space-y-4 text-lg text-neutral-800">
      <p>
        You make a key in the Edge City portal and paste it once, on this site. Not into a chat.
      </p>
      <p>
        We lock the key inside a token right away and hand the token to your AI app. We don't keep a
        copy. There's no database.
      </p>
      <p>
        When your AI asks “what's on tonight?”, the app sends the token back. We unlock it for that
        one request, ask EdgeOS as you, send the answer, and forget the key.
      </p>
      <p>
        Your AI only ever sees the answers. If you want to stop, delete the key in the Edge City
        portal. Everything stops working at once.
      </p>
      <Mermaid
        caption="Your key is entered once, then only ever travels locked."
        chart={`flowchart LR
  You[You] -->|paste key once| Page[Our connect page]
  Page -->|locked token| App[Claude / ChatGPT]
  App -->|locked token with each question| Server[Our server]
  Server -->|your key, for one request| EdgeOS[EdgeOS]
  EdgeOS -->|events| Server -->|answer, no key| App`}
      />
    </div>
  );
}

export function Analogy() {
  return (
    <div className="space-y-4 text-lg text-neutral-800">
      <p>
        Think of your key as a letter. On the connect page you seal it in an envelope that only our
        letter opener can open.
      </p>
      <p>
        Your AI app keeps the sealed envelope. We keep the letter opener, but no envelopes: we have
        nowhere to store them.
      </p>
      <p>
        Each time your AI needs something, it hands us the envelope. We open it, use the letter for
        that one errand, and give the envelope back. Nothing is filed away.
      </p>
      <p>
        Your AI carries the envelope but can't open it. We could read a letter only if someone
        handed us the envelope, and the only way to collect envelopes would be to change the code,
        in public, where anyone can see it.
      </p>
      <Mermaid
        caption="We hold the opener, never the envelopes."
        chart={`sequenceDiagram
  participant A as Your AI app
  participant S as Our server (has the opener)
  participant E as EdgeOS
  A->>S: here's the sealed envelope + question
  S->>S: open, read the letter
  S->>E: errand, as you
  E-->>S: result
  S-->>A: answer (envelope stays with the app)`}
      />
    </div>
  );
}

export function Technical() {
  return (
    <div className="space-y-4 text-neutral-800">
      <p>
        This server is its own OAuth 2.1 authorization server, with no storage. Every artifact it
        issues is a compact JWE (<code>alg: dir</code>, <code>enc: A256GCM</code>) under{" "}
        <code>TOKEN_SECRETS</code>, with a <code>typ</code> claim so a code can't pass as a token:
      </p>
      <ul className="list-disc pl-5">
        <li>
          DCR <code>client_id</code>: redirect URIs and app type (CIMD clients use their metadata
          URL instead)
        </li>
        <li>Auth code (60 s): key, scopes, popup, client, redirect URI, PKCE challenge</li>
        <li>
          Access token (1 h, audience <code>/api/mcp</code>) and refresh token (until 15 Nov 2026)
        </li>
        <li>Proposal code (10 min): the exact write the attendee will confirm</li>
      </ul>
      <p>
        PKCE S256 is required; the authorize redirect includes <code>iss</code> (RFC 9207). The
        secret is generated by a script that writes it to the host's write-only env, so the operator
        never holds it.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full min-w-[560px] border-collapse text-sm">
          <thead>
            <tr className="border-b text-left">
              <th className="py-2">Who</th>
              <th>Can they see your key?</th>
            </tr>
          </thead>
          <tbody>
            {[
              ["The AI model", "No. Tools return results only; keys are scrubbed from errors."],
              ["Your AI app (claude.ai, ChatGPT)", "No. It stores a sealed token it can't open."],
              [
                "The operator, from logs or a database",
                "No. There is no database, and nothing logs headers or keys.",
              ],
              [
                "The operator holding the secret alone",
                "No. Tokens exist only in your app; the secret opens nothing by itself.",
              ],
              [
                "The operator changing the code",
                "Only by deploying code that captures keys, visible in this public repo's history.",
              ],
            ].map(([w, a]) => (
              <tr key={w} className="border-b align-top">
                <td className="py-2 pr-4 font-medium">{w}</td>
                <td className="py-2">{a}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p>
        Trade-offs we accept: a 60-second code could be replayed, but redeeming it also needs the
        PKCE verifier only your app holds; a single token can't be revoked server-side, so revoke
        the key in EdgeOS instead.
      </p>
      <Mermaid
        caption="Connect flow (MCP 2026-07-28, with 2025-era clients supported)."
        chart={`sequenceDiagram
  participant C as MCP client
  participant B as Your browser
  participant S as This server
  participant E as EdgeOS
  C->>S: POST /api/mcp (no token)
  S-->>C: 401 + resource metadata
  C->>S: metadata, CIMD or DCR
  C->>B: open /oauth/authorize (PKCE)
  B->>S: paste key on /connect
  S->>E: validate key, detect scopes
  S-->>B: redirect: sealed code + iss
  B->>C: code
  C->>S: /oauth/token + verifier
  S-->>C: sealed access + refresh
  C->>S: tool call with sealed token
  S->>E: Bearer eos_live_… (in memory only)`}
      />
    </div>
  );
}

export function Verify() {
  const b = buildInfo();
  const at = (p: string) =>
    b.commit === "unknown" ? `${b.repo}/blob/main/${p}` : `${b.repo}/blob/${b.commit}/${p}`;
  const prompt = `Audit these files from ${b.repo} at commit ${b.commit}. Tell me whether an EdgeOS key (eos_live_…) could be stored, logged, returned to an AI, or sent anywhere other than api.edgeos.world: ${KEY_FILES.map((f) => at(f.path)).join(" ")}`;
  return (
    <div className="space-y-4 text-neutral-800">
      <p>
        Read the code that handles your key yourself, or ask your AI to. These links point at the
        exact commit running now:
      </p>
      <ul className="space-y-2">
        {KEY_FILES.map((f) => (
          <li key={f.path}>
            <a className="font-mono underline" href={at(f.path)}>
              {f.path}
            </a>
            : <span className="text-neutral-600">{f.why}</span>
          </li>
        ))}
      </ul>
      <Mermaid
        caption="You or your AI read the key files at the commit this server runs, then check it here and in /api/build-info."
        chart={`flowchart LR
  R[Public repo on GitHub] --> C[Commit ${b.commit.slice(0, 12)}]
  C -->|built and deployed| S[This server]
  S -->|shows its commit| Y[You or your AI]
  Y -->|read the key files| C`}
      />
      <p>Paste this into your AI:</p>
      <pre className="overflow-x-auto whitespace-pre-wrap rounded-lg bg-neutral-100 p-3 text-sm">
        {prompt}
      </pre>
      <h3 className="font-display text-lg font-semibold">
        What is proven, and what you still trust
      </h3>
      <p>
        <b>Proven by the public code:</b> how the key is handled, if the running commit is the one
        shown.
      </p>
      <p>
        <b>Still trusted:</b> that the host really runs that commit. We hold the host login, so we
        could deploy something else. Next steps we plan: deploys only from GitHub's CI with signed
        build records, and later a hardware enclave that proves which code is running.
      </p>
      <h3 className="font-display text-lg font-semibold">What we measure</h3>
      <p>
        Analytics only runs when it is configured. Per tool call: tool name, success or error,
        duration, which AI app, the AI's one-line reason for the call, the popup slug, your key's
        scopes, a conversation id the AI passes back so calls in one chat group together, and a
        hashed id that can't be turned back into your key or name. PostHog also records requests the
        AI makes for features we don't have. The reason and those requests are both short texts
        written by the AI. Never: what you asked, event details, error text, names, or your key.
        Hosting reviews, only when enabled, send the proposed event's text (not your key, not
        attendee lists) to a second AI model to check it against our guidelines.
      </p>
      <p>
        <b>Web pages:</b> these pages send landing_viewed, trust_viewed, how_it_works_viewed,
        connect_viewed, setup_path_selected (new or techy), client_tab_selected (which app guide you
        opened), tutorial_step_viewed (which step number), connect_started, key_accepted (your key's
        scopes) and key_rejected (a short reason such as invalid_key). Page URLs are sent with query
        strings and fragments stripped. No cookies (memory only), no session recordings, no
        heatmaps, no autocapture.
      </p>
    </div>
  );
}
